# fly.toml app configuration file generated for spring-example-project-weathered-snowflake-5201 on 2024-03-24T19:13:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spring-example-project-weathered-snowflake-5201'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
